/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubespbo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 *
 * @author Fadhilah Muhammad F
 */
public class admin extends javax.swing.JFrame {
    
    DefaultTableModel model;
    /**
     * Creates new form NewJFrame
     */
    public admin() {
        initComponents();
        setLocationRelativeTo(this);
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
        String [] rows = {"no", "Nama Kereta", "Kota Asal", "Kota Tujuan", "Jumlah Kursi", "Waktu Keberangkatan"};
        model = new DefaultTableModel(rows, 0);
        tabelKereta.setModel(model);
        
        shows();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelKereta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        namaKereta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kotaAsal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kotaTujuan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jumlahKursi = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jam = new javax.swing.JSpinner();
        detik = new javax.swing.JSpinner();
        menit = new javax.swing.JSpinner();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        edit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelKereta.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tabelKereta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKereta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKeretaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelKereta);

        jScrollPane1.setViewportView(jScrollPane2);

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setText("Data Kereta");

        namaKereta.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        namaKereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaKeretaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setText("Nama Kereta");

        kotaAsal.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        kotaAsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotaAsalActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setText("Kota Asal");

        kotaTujuan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        kotaTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotaTujuanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setText("Kota Tujuan");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel5.setText("Jumlah Kursi");

        jumlahKursi.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel6.setText("Waktu Keberangkatan");

        jam.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        detik.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        menit.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        tambah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        hapus.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        edit.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(menit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(detik, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapus))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jumlahKursi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addComponent(kotaTujuan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kotaAsal, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(namaKereta, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaKereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kotaAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kotaTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlahKursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(edit)
                    .addComponent(hapus))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaKeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaKeretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaKeretaActionPerformed

    private void kotaAsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotaAsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kotaAsalActionPerformed

    private void kotaTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotaTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kotaTujuanActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        try {
            Koneksi conn = new Koneksi();
            Object jml = jumlahKursi.getValue();

            String query = "INSERT INTO kereta (nama_kereta, keberangkatan, tujuan, jumlah_tersedia, waktu_keberangkatan) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement stm = conn.koneksi().prepareStatement(query);

            stm.setString(1, namaKereta.getText());
            stm.setString(2, kotaAsal.getText());
            stm.setString(3, kotaTujuan.getText());
            stm.setInt(4, (int)jml);
            stm.setString(5, jam.getValue().toString() + ":" + menit.getValue().toString() + ":" + detik.getValue().toString());

            int rowsInserted = stm.executeUpdate();
            if (namaKereta.getText().equals("") || 
                    kotaAsal.getText().equals("") || 
                    kotaTujuan.getText().equals("") || 
                    jumlahKursi.getValue().equals("") || 
                    jam.getValue().equals("") || 
                    menit.getValue().equals("") || 
                    detik.getValue().equals("")) {
                JOptionPane.showMessageDialog(null, "Form harus diisi semua!");
            } else {
                JOptionPane.showMessageDialog(null, "Input Berhasil");
                shows();
                hapusInput();
            }

            stm.close();
            conn.koneksi().close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_tambahActionPerformed
    private String id = "";

    private void hapusInput(){
        namaKereta.setText("");
                kotaAsal.setText("");
                kotaTujuan.setText("");
                jumlahKursi.setValue(0);
                jam.setValue(0);
                menit.setValue(0);
                detik.setValue(0);
    }
    private void tabelKeretaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKeretaMouseClicked
        // TODO add your handling code here:
        int baris = tabelKereta.rowAtPoint(evt.getPoint());
        
        this.id = tabelKereta.getValueAt(baris, 0).toString();
        
        String nama = tabelKereta.getValueAt(baris, 1).toString();
        namaKereta.setText(nama);
        
        String asal = tabelKereta.getValueAt(baris, 2).toString();
        kotaAsal.setText(asal);
        
        String tujuan = tabelKereta.getValueAt(baris, 3).toString();
        kotaTujuan.setText(tujuan);
        
        String jml = tabelKereta.getValueAt(baris, 4).toString();
        int jmlValue = Integer.parseInt(jml);
        jumlahKursi.setValue(jmlValue);
        
        String timeString = tabelKereta.getValueAt(baris, 5).toString();
        int hour = Integer.parseInt(timeString.substring(0, 2));
        int minute = Integer.parseInt(timeString.substring(3, 5));
        int second = Integer.parseInt(timeString.substring(6, 8));
        
        jam.setValue(hour);
        menit.setValue(minute);
        detik.setValue(second);
    }//GEN-LAST:event_tabelKeretaMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        
        
        try {
            Koneksi conn = new Koneksi();
            Object jml = jumlahKursi.getValue();

            String query = "DELETE FROM `kereta` WHERE `kereta`.`id_kereta` = " + this.id;
            PreparedStatement stm = conn.koneksi().prepareStatement(query);
            int rowsAffected = stm.executeUpdate(query);
            conn.koneksi().close();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            shows();
            hapusInput();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try {
            Koneksi conn = new Koneksi();
            Object jml = jumlahKursi.getValue();

            String query = "UPDATE `kereta` SET `nama_kereta` = '" + namaKereta.getText() + "', `keberangkatan` = '" + kotaAsal.getText() + "', `tujuan` = '" + kotaTujuan.getText() + "', `jumlah_tersedia` = '" + jumlahKursi.getValue() + "', `waktu_keberangkatan` = ' " + jam.getValue() + ":" + menit.getValue() + ":" + detik.getValue() + "' WHERE `kereta`.`id_kereta` = " + this.id;
            PreparedStatement stm = conn.koneksi().prepareStatement(query);

            int rowsInserted = stm.executeUpdate();
            if (namaKereta.getText().equals("") || 
                    kotaAsal.getText().equals("") || 
                    kotaTujuan.getText().equals("") || 
                    jumlahKursi.getValue().equals("") || 
                    jam.getValue().equals("") || 
                    menit.getValue().equals("") || 
                    detik.getValue().equals("")) {
                JOptionPane.showMessageDialog(null, "Form harus diisi semua!");
            } else {
                JOptionPane.showMessageDialog(null, "Input Berhasil");
                shows();
                hapusInput();
            }

            stm.close();
            conn.koneksi().close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TestTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TestTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TestTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TestTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TestTable().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner detik;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jam;
    private javax.swing.JSpinner jumlahKursi;
    private javax.swing.JTextField kotaAsal;
    private javax.swing.JTextField kotaTujuan;
    private javax.swing.JSpinner menit;
    private javax.swing.JTextField namaKereta;
    private javax.swing.JTable tabelKereta;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables

    private void shows() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nama Kereta");
        model.addColumn("Kota Asal");
        model.addColumn("Kota Tujuan");
        model.addColumn("Jumlah Kursi");
        model.addColumn("Waktu keberangkatan");
        
        Koneksi koneksi = new Koneksi();
        
        try {
            String sql = "SELECT * FROM kereta";
            java.sql.Connection conn = (Connection)koneksi.koneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getInt(1),res.getString(2) ,res.getString(3) ,res.getString(4), res.getString(5), res.getString(6)});                
            }
            tabelKereta.setModel(model);
            
        } catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
}
